# AWS Config
instance_name = "Jenkins"
aws_access_key = ""
aws_secret_key = ""
aws_region = "ap-south-1"
ami = "ami-0912f71e06545ad88"
instance_type = "t2.micro"
key_name = "jenkins-test-2"
type = "jenkins"
