variable "vpc_cidr" {}
variable "vpc_name" {}
variable "availability_zone" {}
variable "public_cidr_block" {}
variable "public_subnet_name" {}
variable "private_cidr_block" {}
variable "private_subnet_name" {}
variable "igw_name" {}
variable "public_rt_name" {}
variable "nat_gw_name" {}
variable "private_rt_name" {}
