# AWS Config
variable "instance_name" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
variable "ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "type" {}
variable "availability_zone" {}
variable "volume_name" {}
variable "vpc_name" {}
variable "public_subnet_name" {}
